# Generated by Django 3.2.8 on 2021-10-15 20:51

import core.utils.models
import django.core.validators
from django.db import migrations, models
import ulid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('asset_id', core.utils.models.CharIDField(default=ulid.ULID, help_text='Ulid-format identifier for this entity.', max_length=30, prefix='cnx_', primary_key=True, serialize=False, unique=True)),
                ('creator', models.CharField(max_length=58)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('decimals', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)])),
                ('frozen', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('metadata', models.CharField(blank=True, max_length=32)),
                ('manager', models.CharField(blank=True, max_length=58)),
                ('reserve', models.CharField(blank=True, max_length=58)),
                ('freeze', models.CharField(blank=True, max_length=58)),
                ('clawback', models.CharField(blank=True, max_length=58)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
