# Generated by Django 3.2.8 on 2021-10-17 04:02

import core.utils.models
from django.db import migrations, models
import ulid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='metadata_64',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=core.utils.models.CharIDField(default=ulid.ULID, editable=False, help_text='Ulid-format identifier for this entity.', max_length=30, prefix='cnx_', primary_key=True, serialize=False, unique=True),
        ),
    ]
