# Generated by Django 3.2.8 on 2021-10-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20211017_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='metadata',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='frozen',
            new_name='default_frozen',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='metadata_hash',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='unit',
            new_name='unit_name',
        ),
        migrations.AddField(
            model_name='asset',
            name='coind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
