# Generated by Django 3.2.8 on 2021-10-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20211017_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
