# Generated by Django 3.2.8 on 2021-10-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
