# Generated by Django 3.2.8 on 2021-10-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata_64',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='metadata_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
