# Generated by Django 3.2.8 on 2021-10-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20211017_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata_64',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='metadata_hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
