# Generated by Django 3.2.8 on 2021-10-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='metadata_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
