# Generated by Django 3.2.8 on 2021-10-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_metadata_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=58)),
                ('asset_name', models.CharField(blank=True, max_length=32)),
                ('unit_name', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
