# Generated by Django 3.2.8 on 2021-10-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_newasset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewAsset',
        ),
    ]
