# Generated by Django 3.2.8 on 2021-10-15 21:13

import core.utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(editable=False)),
                ('account_id', core.utils.models.CharIDField(default=ulid.ULID, help_text='Ulid-format identifier for this entity.', max_length=30, prefix='adr_', primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=58)),
                ('private_key', models.CharField(max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
