# Generated by Django 3.2.8 on 2021-10-17 04:02

import core.utils.models
from django.db import migrations
import ulid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=core.utils.models.CharIDField(default=ulid.ULID, editable=False, help_text='Ulid-format identifier for this entity.', max_length=30, prefix='adr_', primary_key=True, serialize=False, unique=True),
        ),
    ]
